SUP-2422: update deprecated keys in getContextKey
evolv-ai/client-integrations pull request #27
Opened 2021-01-19 22:11 UTC by timcubb

Currently getContextKey is returning "contaminations" or "confirmations", which is throwing a deprecated warning in the console, stating to use `experiments.contaminations` and `experiments.confirmations` instead.

2021-01-19 23:00 UTC, robertsevernsentient approved these changes

2021-01-19 23:03 UTC, robertsevernsentient commented
Hey @timcubb -- can you review this PR before commting this?
https://github.com/evolv-ai/client-integrations/pull/25

Also -- can you add the same change for this file analytics/adobe-analytics/experience-accelerator/src/Client.ts?

2021-01-19 23:04 UTC, robertsevernsentient requested changes
Please add the same change for analytics/adobe-analytics/experience-accelerator/src/Client.ts

2021-01-20 02:49 UTC, timcubb commented
> Please add the same change for analytics/adobe-analytics/experience-accelerator/src/Client.ts

@robertsevernsentient - I will rebase and add to AA now that your PR is merged.

2021-01-20 16:36 UTC, timcubb commented
> Hey @timcubb -- can you review this PR before commting this?
> #25
> 
> Also -- can you add the same change for this file analytics/adobe-analytics/experience-accelerator/src/Client.ts?

@robertsevernsentient - I have rebased and added the change to AA.

2021-01-20 17:14 UTC, robertsevernsentient approved these changes

2021-01-26 03:35 UTC, teolisitza approved these changes

2021-01-26 03:35 UTC, merged